apiVersion: apps/v1 # for kubectl versions >= 1.9.0 use apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-api-deployment
  template:
    metadata:
      labels:
        app: my-api-deployment
    spec:
      containers:
      - name: my-api-pod
        image: lbgpaul/fastapi-simple
        ports:
        - containerPort: 9080

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  ports:
  - port: 3080
    nodePort: 30380
    targetPort: 9080
  selector:
    app: my-api-deployment
